apiVersion: v1
kind: Service
metadata:
  name: {{ include "ai-platform.fullname" . }}-learner-api
spec:
  type: {{ .Values.service.type }}
  selector:
    app: {{ include "ai-platform.name" . }}
    component: learner-api
  ports:
    - port: {{ .Values.service.port }}
      targetPort: {{ .Values.service.port }}
      protocol: TCP
      name: http
