{{- if .Values.secrets.secretName }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.secrets.secretName }}
type: Opaque
stringData:
  # Use `kubectl create secret generic --from-env-file` as recommended; file left intentionally empty
  # DATABASE_URL: ""
  # REDIS_URL: ""
{{- end }}
